### ISSUE TITLE
No comments in the code

### ISSUE THREAD

**Issue by chawlanikhil24** [cloud-bulldozer/benchmark-wrapper#15]
So, to begin with the wrapper scripts for smallfile, I tried to go through the code for currently available benchmarks. But it was quite rough to go through, since, there were no comments added in the code. I highly recommend to follow this good practice to add comments in the code, which is currently residing and upcoming in snafu.

**Comment by aakarshg** [comment]
Although I understand the reason behind this, i'll need to point out that snafu so far has been just a bunch of scripts to help do the job of processing raw benchmark data. That being said, code that needs comments can already be called bad code. 

Adding enhancement label, so we can look at polishing code sometime in the future, but not a high priority.

**Comment by bengland2** [comment]
I think this can be closed because the postprocessing has been rewritten to use run_snafu.py, which is documented, and it is a lot smaller because of this.
