### ISSUE TITLE
Write data to file if no ES is provided or fails

### ISSUE THREAD

**Issue by dry923** [cloud-bulldozer/benchmark-wrapper#218]
If would be useful to write the data to be indexed to a file in the case where ES fails or is not provided.This would allow us to retrieve the data seperately and not have to do a full re-run if an issue is hit.

**Comment by dry923** [comment]
@acalhounRH We briefly talked about this during the call last week. Please add your thoughts.

**Comment by acalhounRH** [comment]
@dry923 Is this taken care of now with --create-archive?

**Comment by dry923** [comment]
@acalhounRH yup PR https://github.com/cloud-bulldozer/benchmark-wrapper/pull/279 resolved it. Thanks again!
