### ISSUE TITLE
Error due to the output file not being found for trigger_fio

### ISSUE THREAD

**Issue by fritchie** [cloud-bulldozer/benchmark-wrapper#234]
I have seen multiple occurrences of the following error in fio client pods:

```
ERROR - MainProcess - trigger_fio: Fio failed to execute
ERROR - MainProcess - trigger_fio: Output file: <fio-server-1-benchmark-f003-drkjc> fio: output file open error: No such file or directory
```
The errors seem to be random. Has anyone else seen this?

**Comment by jtaleric** [comment]
cc @acalhounRH @bengland2

**Comment by fritchie** [comment]
I see an occurrence of the error in 

https://github.com/cloud-bulldozer/benchmark-wrapper/pull/168

**Comment by jtaleric** [comment]
ack... @rsevilla87

**Comment by rsevilla87** [comment]
@fritchie, have you hit this bug recently?
Closing this issue. In case you run into this again, open or re-open a new issue providing more information of the specs of the test you are performing.
