### ISSUE TITLE
Inefficient indexing 

### ISSUE THREAD

**Issue by acalhounRH** [cloud-bulldozer/benchmark-wrapper#24]
Currently indexing is performed by opening a connection to elasticsearch for each test and document type, the recommended method would be to open a single connection and as documents are created/parsed those documents are emitted to the indexer, this can be achieved with the utilization of  py_es_bulk and python generators. 

pseudo code follows:

**main ()**:
  handle args 
  initialize es
  status = py_es_bulk.streaming_bulk(es, process_generator(args)

**def process_generator(args)**
  object_generator = process_data(args)

  for obj in object_generator:
    for action in obj.emit_actions():
       yield action

**def process_data(args)**

for i in args.sample: 
  trigger_fio_generator = **_trigger_fio(args)** # _trigger_fio would become an object containing the emit_actions method 
  yield trigger_fio_generator

**Comment by jtaleric** [comment]
Yup - we need a shared library for all the workloads to inherit. This is on the backlog - if you have cycles, it would be great to see this added!

**Comment by acalhounRH** [comment]
I do have cycles for this, I just need to update snafu to produce the calculated averages then I can switch to updating it to use py_es_bulk.

**Comment by acalhounRH** [comment]
*This work would be for fio-wrapper.py, but the py_es_bulk module could be used for all wrappers later on.

**Comment by acalhounRH** [comment]
First attempt at solving this issue.

https://github.com/acalhounRH/snafu/tree/added_logging_and_py_es_bulk

**Comment by acalhounRH** [comment]
implemented run_snafu.py and update fio-wrapper to be compatible, last item to resolve to make this fully functional is resolving import errors. 

https://github.com/acalhounRH/snafu/tree/added_run_snafu

With the use of run_snafu ripsaw is able to have a single point of accessing snafu and ensures all wrappers are indexing data the same way into elasticsearch. Instead of each x_wrapper script implementing indexing separately, run_snafu handles all indexing, with the expectation that x_wrapper would execute its test, parse its own data, and yield back normalized document/index pairs.

**Comment by acalhounRH** [comment]
The core of the issue is resolved with PR 38, the remaining amount of work is moving existing Benchmarks over to the new structure.

**Comment by rsevilla87** [comment]
All workloads use the same indexing bits.
