### ISSUE TITLE
Add test case for upgrade wrapper

### ISSUE THREAD

**Issue by chaitanyaenr** [cloud-bulldozer/benchmark-wrapper#260]
Benchmark-wrapper needs to test the upgrade wrapper similar to other wrappers in the CI to make sure the code changes are not breaking the functionality. The version to upgrade to can be set to the same version as the CI version to avoid upgrading the OpenShift cluster on which CI is running.

**Comment by jtaleric** [comment]
I think this is more specific to OpenShift -- that functionality of CI should be outside of benchmark-wrapper.
