### ISSUE TITLE
Improve documentation for supported wrappers

### ISSUE THREAD

**Issue by chaitanyaenr** [cloud-bulldozer/benchmark-wrapper#266]
We have documentation around the supported workload wrappers and how to a new workload wrapper, it might be useful to add information around things like brief description about the benchmark as well as the wrapper, metrics it collects/indexes, and instructions on how to run the wrapper locally using podman.

**Comment by jtaleric** [comment]
@chaitanyaenr hey! have you seen the update to our docs that @learnitall just had merged in?

**Comment by jtaleric** [comment]
https://benchmark-wrapper.readthedocs.io/en/latest/
