### ISSUE TITLE
Invalid name(s) for python module

### ISSUE THREAD

**Issue by acalhounRH** [cloud-bulldozer/benchmark-wrapper#32]
All wrapper(script) names and directory names need to be changed to be complaint with python module syntax standards, if this is not resolved python will not import those modules. 

**change dash "-" to underscore "_"** in all directory names and script names.

https://docs.python.org/3/reference/lexical_analysis.html#identifiers

**Comment by aakarshg** [comment]
Instead of having` _` or `-` in the names, i'd recommend we just move to just benchmark name and get rid of wrapper altogether.

**Comment by rsevilla87** [comment]
Snafu meets pep8 style at the moment, closing
