### ISSUE TITLE
Quay trigger sometimes fails

### ISSUE THREAD

**Issue by rsevilla87** [cloud-bulldozer/benchmark-wrapper#325]
I've figured out why the quay trigger to build the container images stored in this repository randomly fails.

I realized that quay reported an error message saying something like "Limit of queued builds reached" when I tried to build an image manually (which wasn't triggered after merging a PR) while some of the build triggers where still running.

Conclusion: We must get away of quay build system ASAP

**Comment by learnitall** [comment]
Tracking progress for a new build system here: https://github.com/cloud-bulldozer/benchmark-wrapper/pull/319
