### ISSUE TITLE
why modify contents of argparse output object?

### ISSUE THREAD

**Issue by bengland2** [cloud-bulldozer/benchmark-wrapper#39]
@acalhounRH  in the development branch [at this line of code](https://github.com/cloud-bulldozer/snafu/blob/6ec5c2b9987e6064530569f785ce06e46302ed13/fio_wrapper/fio_wrapper.py#L45) I see this:

```
self.args.cluster_name = "mycluster"
if "clustername" in os.environ:
    self.args.cluster_name = os.environ["clustername"]
```
the args structure is generated by argparse module.  In all other fields you extract data from this structure but you don't modify it, why are you doing that here?  Think you meant to do 

```
self.cluster_name = 'mycluster'
if "clustername" in os.environ:
    self.cluster_name = os.environ["clustername"]
```

**Comment by acalhounRH** [comment]
Must be typo, that change wouldn't affect anything. Shouldn't be a problem to change.

**Comment by aakarshg** [comment]
this is a good catch @bengland2 , so far the code has been just in there to get things done. we should look at cleaning it, have noticed couple of other places too where the code modifed argparse output object.
