### ISSUE TITLE
Elasticsearch: credential authentication

### ISSUE THREAD

**Issue by ebattat** [cloud-bulldozer/benchmark-wrapper#400]
The current status is that ElasticSearcn is not under authentication (user+password).
Is there option to add authentication(user+password) for the elsticsearch url ?

**Comment by jtaleric** [comment]
> The current status is that ElasticSearcn is not under authentication (user+password). Is there option to add authentication(user+password) for the elsticsearch url ?

@ebattat why do you think it is `not under authentication`? Today we accept a ES URL, which can have the user/pass passed. Most of our servers (minus the public ones) use authentication for read/write to ES.

`'http://<username>:<password>@<host>'`

**Comment by ebattat** [comment]
@jtaleric. Thx for your fast replay.
Can I use also https instead http ?

**Comment by jtaleric** [comment]
> 

yes? why wouldn’t you be able to assuming your server supports https.

**Comment by ebattat** [comment]
@jtaleric, last query before closing, Did benchmark-wrapper handle https certificate or verify_certs=False ?

**Comment by jtaleric** [comment]
> @jtaleric, last query before closing, Did benchmark-wrapper handle https certificate or verify_certs=False ?

https://github.com/cloud-bulldozer/benchmark-wrapper/blob/master/snafu/run_snafu.py#L94-L100
