### ISSUE TITLE
perf-lta-es not the clustername

### ISSUE THREAD

**Issue by bengland2** [cloud-bulldozer/benchmark-wrapper#92]
When I run smallfile wrapper, run_snafu.py logs these messages below, and the cluster_name is wrong, not sure where perf-lta-es comes from as a cluster name but I did not specify it at all, either in the wrapper or in env. vars.

```
2019-11-04T15:33:33Z - INFO     - MainProcess - 
run_snafu: Connected to the elasticsearch cluster with info as follows:
{
u'cluster_name': u'perf-lta-es', 
u'cluster_uuid': u'fLlQtf5cTiqtRoc02RaQdQ', 
u'version': {u'build_date': u'2019-09-06T14:40:30.409026Z', 
u'minimum_wire_compatibility_version': u'6.8.0', 
u'build_hash': u'1c1faf1', 
u'number': u'7.3.2', 
u'lucene_version': u'8.1.0', 
u'minimum_index_compatibility_version': u'6.0.0-beta1', 
u'build_flavor': u'default', 
u'build_snapshot': False, 
u'build_type': u'rpm'}, 
u'name': u'perf-es-1', 
u'tagline': u'You Know, for Search'
}
2019-11-04T15:33:33Z - INFO     - MainProcess - 
wrapper_factory: identified smallfile as the benchmark wrapper
```

Can we not print stuff that's overridden in the wrapper?  Or make more common variables inherited by all wrappers (i.e. not implemented in per-wrapper parsing)?   I could help with this.

**Comment by aakarshg** [comment]
When run in the INFO mode for logging, snafu would print the output for es.info(). The cluster_name you see here is the name given to the elasticsearch cluster and is completely different from the cluster_name we pass to snafu. The variable is not being overridden in anyway. 

Hope it helps and makes sense.

**Comment by bengland2** [comment]
So is the ES cluster uuid also not related to the test?      Then I'll check that snafu benchmarks log the user-input parameters and ripsaw test uuid separately.     If not, they should.

**Comment by aakarshg** [comment]
yes @bengland2 the cluster_uuid you see above is that off the elasticsearch clusters and in no way related to the uuid that the user passes ( the uuid related to the benchmark )

**Comment by bengland2** [comment]
So instead of "connected to elastic search cluster with info as follows" let's say "elastic search cluster info (not benchmark info):"   That way people won't get confused.   run_snafu.py should be modified at least, and also run_snafu.py should log test cluster parameters such as cluster name, uuid, user, etc.  if it isn't already.

**Comment by bengland2** [comment]
this isn't really an issue, just a slight change in wording would clarify the message a bit, but no big deal.
